version: "3.9"
services:
  cobs-cicd:
    build:
      context: .
      dockerfile: Dockerfile
    image: cobs-cicd:latest
    container_name: cobs-cicd
    volumes:
#      - .:/srv/nama_folder # sama dengan path dibawah
       - /home/devsintek/docker/cobaCICD:/srv/cobaCICD
       - /srv/cobaCICD/node_modules
    ports:
      - "62303:62303"
    command: npm start
    restart: unless-stopped
networks:
  default:
    external:
      name: mariadb_default
